mysite/moticom/urls.py
from django.urls import path
from . import views

app_name = 'moticom'
urlpatterns = [
    path('', views.TopView.as_view(), name='index'),
    path('board', views.BoardView.as_view(), name='board'),
    path('report/', views.ReportView.as_view(), name='report'),
    path('complaints', views.ComplaintsView.as_view(), name='complaints'),
    path('help', views.HelpView.as_view(), name='help'),
    path('admin', views.AdminView.as_view(), name='admin'),
    path('report/SC-03', views.CreateView.as_view(), name='SC-03'),
    path('report/SC-04', views.SceretView.as_view(), name='SC-04'),
    path('report/SC-05', views.CompleteView.as_view(), name='SC-05'),
    path('SC-08/', views.CompleteView.as_view(), name='SC-08')

    ]

mysite/moticom/views.py
from django.shortcuts import render
from django.views import generic

class TopView(generic.TemplateView):
    template_name = 'moticom/index.html'


class BoardView(generic.TemplateView):
    template_name = 'moticom/board.html'
    

class ReportView(generic.TemplateView):
    template_name = 'moticom/report.html'
    

class ComplaintsView(generic.TemplateView):
    template_name = 'moticom/complaints.html'
    

class HelpView(generic.TemplateView):
    template_name = 'moticom/help.html'
    
    
class AdminView(generic.TemplateView):
    template_name = 'moticom/admin.html'
    
class CreateView(generic.TemplateView):
    template_name = 'moticom/SC-03.html'
    
class SceretView(generic.TemplateView):
    template_name = 'moticom/SC-04.html'
    
class CompleteView(generic.TemplateView):
    template_name = 'moticom/SC-05.html'
    
class CompleteView(generic.TemplateView):
    template_name = 'moticom/SC-08.html'

mysite/moticom/templates/moticom/SC-03.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <title>報告画面</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>
  <div class="row justify-content-md-center">
    <div class="col-md-6">
      <div class="container mt-5">
        <form class="card">
          <div class="card-header">報告画面</div>
          <div class="card-body">
            <h5 class="card-title">ここにインシデントのタネを記入してください</h5>
            <p class="card-text">※インシデントのタネとは？ --あわよくば事故に繋がるようなミスのこと。</p>
            <p class="card-text">例: 機密情報を添付したメール宛先が社外の人に設定されていた等</p>
            <p class="card-text">NGワード: ---------</p>
            <label class="form-label">記入内容</label>
            <textarea  class="form-control" id="report_text" cols="50" rows="6" maxlength="300" onkeyup="ShowLength(value);"></textarea>
            <p id="inputlength">残り300字</p>
            <script>
              function ShowLength(str) {
                document.getElementById("inputlength").innerHTML = "残り" + (300 - str.length) + "字"
              }
            </script>
          </div>
          <div class="card-footer" style="text-align: center;">
            <div class="btn-group" role="group" aria-label="Basic example">
              <a class="btn btn-primary" href="{% url 'moticom:report' %}"  role="button">戻る</a>
              <a class="btn btn-primary" href="{% url 'moticom:SC-04' %}" role="button">次へ</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</body>

</html>

mysite/moticom/templates/moticom/SC-04.html
<!doctype html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <title>ジャンル決定画面</title>
</head>

<body>
  <div class="row justify-content-md-center">
    <div class="col-md-6">
      <div class="container mt-5">
        <form class="card">
          <div class="card-header">ジャンルの選択画面</div>
          <div class="card-body">
            <h5 class="card-title">以下より、もっとも当てはまるジャンルを選択してください</h5>
            <div class="form-check" style="padding-bottom: 2%;">
              <input class="form-check-input" type="radio" name="input_radio" value="A" checked>
              <label class="form-check-label">
                メール系
              </label>
            </div>
            <div class="form-check" style="padding-bottom: 2%;">
              <input class="form-check-input" type="radio" name="input_radio" value="B">
              <label class="form-check-label">
                パスワード系
              </label>
            </div>
            <div class="form-check" style="padding-bottom: 2%;">
              <input class="form-check-input" type="radio" name="input_radio" value="C">
              <label class="form-check-label">
                持ち出し系
              </label>
            </div>
            <div class="form-check" style="padding-bottom: 2%;">
              <input class="form-check-input" type="radio" name="input_radio" value="D">
              <label class="form-check-label">
                〇〇〇系
              </label>
            </div>
            <div class="form-check" style="padding-bottom: 2%;">
              <input class="form-check-input" type="radio" name="input_radio" value="E">
              <label class="form-check-label">
                △△△系
              </label>
            </div>
          </div>
          <div class="card-footer" style="text-align: center; padding-left: 80%;">
            <a class="btn btn-primary" href="{% url 'moticom:SC-05' %}" role="button">送信</a>
          </div>
        </form>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>

</html>

mysite/moticom/templates/moticom/SC-05.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <title>投稿画面</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>
  <div class="row justify-content-md-center">
    <div class="col-md-6">
      <div class="container mt-5">
        <form class="card">
          <div class="card-header">投稿画面</div>
          <div class="card-body">
            <h5 class="card-title">投稿内容</h5>
            <textarea class="form-control" name="input_textarea" rows="5" cols="80" maxlength="300">
              報告内容をここに表示するイメージです
              報告内容をここに表示するイメージです
              報告内容をここに表示するイメージです
            </textarea>
          </div>
          <div class="mb-3 row" style="padding-left: 20px;">
            <label for="staticEmail" class="col-sm-2 col-form-label">ジャンル</label>
            <div class="col-sm-10">
              <input class="form-control" type="text" placeholder="メール関連" aria-label="Disabled input example" disabled>
            </div>
          </div>
          <div class="card-footer" style="text-align: center;">
            <a class="btn btn-primary" href="{% url 'moticom:index' %}" role="button">topに戻る</a>
          </div>
      </div>
      </form>
    </div>
  </div>
  </div>
</body>

</html>

mysite/moticom/templates/moticom/SC-08.html
<!doctype html>
<html lang="ja">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <title>プロフィール管理画面</title>
</head>

<body>
  <div class="row justify-content-md-center" style="padding-top: 40px;">
    <div class="card mb-3" style="max-width: 800px;">
      <div class="row g-0">
        <h1 class="card-title" style="padding-bottom: 50px;">プロフィール</h1>
        <div class="col-md-4">
          <img src="assets/images/bs-images/img-2x2.png" class="img-thumbnail" alt="rounded-circle">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <p class="card-text">ユーザー名</p>
            <span class="border border-dark border-1"></span>
            <p class="card-text">メールアドレス</p>
            <span class="border border-dark border-1"></span>
            <p class="card-text">パスワード</p>
            <span></span>
            <div style="text-align: center; padding-left: 70%;">
              <a class="btn btn-primary" href="#" role="button">パスワードの変更</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>
</body>

</html>

mysite/moticom/templates/moticom/admin.html
{% extends "moticom/admin_base.html" %}

{% block extra_css %}
<style type="text/css">
    #analysis {background: rgb(255, 0, 0);}
</style>
{% endblock %}

{% block title %}Moticom{% endblock title %}

{% block content %}
    <div class="container">
        <h2 class="mt-4 border-bottom">分析結果</h2>
        <div></div>
        <h2 class="mt-2 border-bottom pb-2">管理策一覧</h2>
    </div> 
{% endblock content %}

mysite/moticom/templates/moticom/admin_base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" style="height: 100%;">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'moticom/css/bootstrap.min.css' %}">
        {% block extra_css %}{% endblock %}
        
        <title>{% block title %}My books{% endblock %}</title>
    </head>
    <!-- ページの共有レイアウト -->
    <body style="height: 100%; margin: 0;">
        <!-- ヘッダー -->
        <header class="d-flex sticky-top" style="height: 40px; margin: 0; background-color:rgb(255, 150, 128);">
            <h2 class="text-white ms-3">Moticom</h2>
        </header>
        <!-- サイドバー＋ページ内容領域（内容は別HTMLファイルに書く） -->
        <main style="display:flex; height: 100%; margin-top: 0;">
            <!-- サイドバー -->
            <div style="width:250px; height: 100%; background-color:rgb(255, 150, 128);">
                <div class="d-flex flex-column text-white" style="position: sticky; top: 40px;">
                    <hr>
                    <ul class="nav nav-pills flex-column mb-auto">
                        <li class="nav-item">
                            <a id="analysis" href="#" class="nav-link text-white">
                                分析結果
                            </a>
                        </li>
                         <li>
                            <a id="user_cr" href="#" class="nav-link text-white">
                                ユーザ確認・登録
                            </a>
                        </li>
                        <li>
                            <a id="layout" href="#" class="nav-link text-white">
                                ユーザ画面調整
                            </a>
                        </li>
                        <li>
                            <a id="genre_manage" href="#" class="nav-link text-white">
                                ジャンル管理
                            </a>
                        </li>
                        <li>
                            <a id="ng_filter" href="#" class="nav-link text-white">
                                フィルター設定
                            </a>
                        </li>
                        <li>
                            <a id="resort" href="#" class="nav-link text-white">
                                報告再振り分け
                            </a>
                        </li>
                        <li>
                            <a id="se_measure" href="#" class="nav-link text-white">
                                セキュリティ対策紐付け・追加
                            </a>
                        </li>
                    </ul>
                    <hr>
                </div>
            </div>
            <!-- ページ内容領域 -->
            <div class="container-fluid">
                {% block content %}
                {{ content }}
                {% endblock %}
            </div>
        </main>
        <!-- フッター -->
        <footer class="footer d-flex align-items-center mt-auto py-3 text-white-50" style="background-color:rgb(255, 150, 128);">
            <small>&copy; 2021 奥原PBL</small>
        </footer>
        <script src="{% static 'moticom/js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'moticom/js/bootstrap.bundle.min.js' %}"></script>
        {% block extra_js %}{% endblock %}
    </body>
</html>

mysite/moticom/templates/moticom/board.html
{% extends "moticom/base.html" %}

{% block extra_css %}
<style type="text/css">
    #board {background: rgb(255, 0, 0);}
</style>
{% endblock %}

{% block title %}Moticom{% endblock title %}

{% block content %}
    <div class="container">
        <h2 class="mt-2 border-bottom pb-2">投稿掲示板</h2>
        <div class="d-flex pt-3">
            <p class="pb-3 mb-0 small lh-sm border-bottom">
                <strong class="d-block">@ユーザー名</strong>
                投稿内容
            </p>
        </div>
    </div> 
{% endblock content %}

mysite/moticom/templates/moticom/complaints.html
{% extends "moticom/base.html" %}

{% block extra_css %}
<style type="text/css">
    #complaints {background: rgb(255, 0, 0);}
</style>
{% endblock %}

{% block title %}Moticom{% endblock title %}

{% block content %}
    <div class="container">
        <h2 class="mt-2 border-bottom pb-2">愚痴掲示板</h2>
        <div class="d-flex pt-3">
            <p class="pb-3 mb-0 small lh-sm border-bottom">
                <strong class="d-block">@ユーザー名</strong>
                投稿内容
            </p>
        </div>
    </div> 
{% endblock content %}

mysite/moticom/templates/moticom/help.html
{% extends "moticom/base.html" %}

{% block extra_css %}
<style type="text/css">
    #help {background: rgb(255, 0, 0);}
</style>
{% endblock %}

{% block title %}Moticom{% endblock title %}

{% block content %}
    <div class="container">
        <h2 class="mt-4 border-bottom">ヘルプ</h2>
        <div></div>
    </div> 
{% endblock content %}

mysite/moticom/templates/moticom/report.html
{% extends "moticom/base.html" %}

{% block extra_css %}
<style type="text/css">
    #report {background: rgb(255, 0, 0);}
</style>
{% endblock %}

{% block title %}Moticom{% endblock title %}

{% block content %}
    <div class="container">
        <h2 class="mt-2 border-bottom pb-2">問題報告</h2>
    </div> 
{% endblock content %}